<?php
declare(strict_types=1);

require_once __DIR__ . '/../../includes/auth.php';
require_once __DIR__ . '/../../includes/lph_module_helpers.php';

requireLogin();
if (!canManage()) {
    setFlash('danger', 'Stakeholder management is limited to authorized staff.');
    redirect(APP_URL . '/dashboard.php');
}

$pdo = db();

try {
    $pdo->exec('SET FOREIGN_KEY_CHECKS = 0');
    $tablesToClean = [
        'attendance',
        'attendance_event_history',
        'attendance_logs',
        'feedback',
        'invitations',
        'qr_codes',
        'registrations',
        'stakeholder_history',
        'survey_submissions',
        'stakeholders'
    ];
    foreach ($tablesToClean as $tbl) {
        try {
            $pdo->exec("TRUNCATE TABLE `$tbl`");
        } catch (Exception $e) {
            $pdo->exec("DELETE FROM `$tbl`");
        }
    }
    $pdo->exec('ALTER TABLE `stakeholders` AUTO_INCREMENT = 1');
    $pdo->exec('ALTER TABLE `qr_codes` AUTO_INCREMENT = 1');
    $pdo->exec('SET FOREIGN_KEY_CHECKS = 1');

    $newStakeholders = [
        [
            'full_name'    => 'Francisco “Isko Moreno” M. Domagoso',
            'organization' => 'Office of the City Mayor',
            'sector'       => 'City Mayor',
            'phone'        => '(02) 8527-0971',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 1,
            'address'      => 'Manila City Hall, Padre Burgos Ave, Ermita, Manila',
        ],
        [
            'full_name'    => 'Angela Lei “Chi” I. Atienza-Valdepeñas',
            'organization' => 'Office of the Vice Mayor / City Council',
            'sector'       => 'Vice Mayor / Presiding Officer',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 1,
            'address'      => 'Manila City Hall, Padre Burgos Ave, Ermita, Manila',
        ],
        [
            'full_name'    => 'Raymundo “Mon” R. Yupangco',
            'organization' => 'Sangguniang Panlungsod',
            'sector'       => 'Majority Floor Leader / City Councilor',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 1,
            'address'      => 'Manila City Hall, Padre Burgos Ave, Ermita, Manila',
        ],
        [
            'full_name'    => 'Timothy Oliver “Tol” I. Zarcal',
            'organization' => 'Sangguniang Panlungsod',
            'sector'       => 'President Pro-Tempore / City Councilor',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 1,
            'address'      => 'Manila City Hall, Padre Burgos Ave, Ermita, Manila',
        ],
        [
            'full_name'    => 'Atty. Hans Roger S. Luna',
            'organization' => 'Office of the City Council',
            'sector'       => 'Secretary to the City Council',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 1,
            'address'      => 'Manila City Hall, Padre Burgos Ave, Ermita, Manila',
        ],
        [
            'full_name'    => 'Cesar B. Chavez',
            'organization' => 'Office of the Chief of Staff',
            'sector'       => 'Chief of Staff',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 1,
            'address'      => 'Manila City Hall, Padre Burgos Ave, Ermita, Manila',
        ],
        [
            'full_name'    => 'Manuel M. Zarcal',
            'organization' => 'Office of the Mayor',
            'sector'       => 'Secretary to the Mayor',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 1,
            'address'      => 'Manila City Hall, Padre Burgos Ave, Ermita, Manila',
        ],
        [
            'full_name'    => 'Atty. Luch R. Gempis, Jr.',
            'organization' => 'Office of the City Legal Officer',
            'sector'       => 'City Legal Officer',
            'phone'        => '(02) 8527-0912',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 1,
            'address'      => 'Manila City Hall, Padre Burgos Ave, Ermita, Manila',
        ],
        [
            'full_name'    => 'Jorjette B. Aquino',
            'organization' => 'City Budget Office',
            'sector'       => 'City Budget Officer',
            'phone'        => '(02) 5302-6731',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 1,
            'address'      => 'Manila City Hall, Padre Burgos Ave, Ermita, Manila',
        ],
        [
            'full_name'    => 'Atty. Eduardo Quintos XIV',
            'organization' => 'Office of the City Administrator',
            'sector'       => 'City Administrator',
            'phone'        => '(02) 8521-7505 / 8527-0984',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 1,
            'address'      => 'Manila City Hall, Padre Burgos Ave, Ermita, Manila',
        ],
        [
            'full_name'    => 'Jonathan R. Galorio',
            'organization' => 'Office of the City Accountant',
            'sector'       => 'Officer-in-Charge',
            'phone'        => '(02) 5310-8285',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 1,
            'address'      => 'Manila City Hall, Padre Burgos Ave, Ermita, Manila',
        ],
        [
            'full_name'    => 'Jocelyn J. Quintos',
            'organization' => 'City Personnel Office',
            'sector'       => 'Officer-in-Charge',
            'phone'        => '(02) 8527-0972',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 1,
            'address'      => 'Manila City Hall, Padre Burgos Ave, Ermita, Manila',
        ],
        [
            'full_name'    => 'Thelma L. Perez',
            'organization' => 'City General Services Office',
            'sector'       => 'Officer-in-Charge',
            'phone'        => '(02) 5310-5318',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 1,
            'address'      => 'Manila City Hall, Padre Burgos Ave, Ermita, Manila',
        ],
        [
            'full_name'    => 'Arsenio M. Riparip',
            'organization' => 'City Security Force',
            'sector'       => 'Officer-in-Charge',
            'phone'        => '(02) 5308-9925',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 1,
            'address'      => 'Manila City Hall, Padre Burgos Ave, Ermita, Manila',
        ],
        [
            'full_name'    => 'Joel M. Par',
            'organization' => 'Manila Barangay Bureau',
            'sector'       => 'Officer-in-Charge',
            'phone'        => '(02) 5302-6878',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 1,
            'address'      => 'Manila City Hall, Padre Burgos Ave, Ermita, Manila',
        ],
        [
            'full_name'    => 'TJ Hizon',
            'organization' => 'Market Administration Office',
            'sector'       => 'Officer-in-Charge',
            'phone'        => '(02) 5310-5773',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 1,
            'address'      => 'Manila City Hall, Padre Burgos Ave, Ermita, Manila',
        ],
        [
            'full_name'    => 'Ar. Ernesto M. Oliveros',
            'organization' => 'Manila Urban Settlements Office',
            'sector'       => 'Officer-in-Charge',
            'phone'        => '(02) 8527-0906',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 1,
            'address'      => 'Manila City Hall, Padre Burgos Ave, Ermita, Manila',
        ],
        [
            'full_name'    => 'Mark Richmund M. de Leon',
            'organization' => 'City Planning & Development Office',
            'sector'       => 'Officer-in-Charge',
            'phone'        => '(02) 5310-6529',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 1,
            'address'      => 'Manila City Hall, Padre Burgos Ave, Ermita, Manila',
        ],
        [
            'full_name'    => 'Atty. Giovanne T. Lim',
            'organization' => 'Office of the City Prosecutor',
            'sector'       => 'City Prosecutor',
            'phone'        => '(02) 8527-8787',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 1,
            'address'      => 'Manila City Hall, Padre Burgos Ave, Ermita, Manila',
        ],
        [
            'full_name'    => 'Enriqueta “Erika” O. Platon',
            'organization' => 'Liga ng mga Barangay – Manila',
            'sector'       => 'President',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 2,
            'address'      => 'Liga ng mga Barangay Office, Manila City Hall',
        ],
        [
            'full_name'    => 'Juliana Rae “Yanyan” M. Ibay',
            'organization' => 'SK Federation – Manila',
            'sector'       => 'President',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 2,
            'address'      => 'SK Federation Office, Manila City Hall',
        ],
        [
            'full_name'    => 'Hon. Danilo V. Hernandez',
            'organization' => 'Barangay 659, Zone 71',
            'sector'       => 'Punong Barangay',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Pending',
            'category_id'  => 2,
            'address'      => 'Barangay Hall, Brgy. 659, Zone 71, Ermita, Manila',
        ],
        [
            'full_name'    => 'Hon. Maria Teresa L. Ramos',
            'organization' => 'Barangay 659, Zone 71',
            'sector'       => 'Barangay Kagawad',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Pending',
            'category_id'  => 2,
            'address'      => 'Barangay Hall, Brgy. 659, Zone 71, Ermita, Manila',
        ],
        [
            'full_name'    => 'Eduardo “Ka Ed” C. Valenzuela',
            'organization' => 'Manila Residents / Manileños',
            'sector'       => 'Community Representative',
            'phone'        => '(02) 8527-1111',
            'email'        => 'Not publicly listed',
            'status'       => 'Pending',
            'category_id'  => 3,
            'address'      => 'Tondo, Manila (District 1)',
        ],
        [
            'full_name'    => 'Christian Joshua “CJ” M. Bautista',
            'organization' => 'Manila Youth Sector',
            'sector'       => 'Youth Representative',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Pending',
            'category_id'  => 3,
            'address'      => 'Sta. Cruz, Manila (District 3)',
        ],
        [
            'full_name'    => 'Lourdes “Nanay Uding” S. Del Rosario',
            'organization' => 'Senior Citizens Sector',
            'sector'       => 'Sector Representative',
            'phone'        => '(02) 8527-3344',
            'email'        => 'Not publicly listed',
            'status'       => 'Pending',
            'category_id'  => 3,
            'address'      => 'Sampaloc, Manila (District 4)',
        ],
        [
            'full_name'    => 'Ramon “Monching” T. Salcedo',
            'organization' => 'PWD Sector – Manila',
            'sector'       => 'Sector Representative',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Pending',
            'category_id'  => 3,
            'address'      => 'Ermita, Manila (District 5)',
        ],
        [
            'full_name'    => 'Carmelita “Lita” G. Mendoza',
            'organization' => "Women's Organization",
            'sector'       => 'Sector Representative',
            'phone'        => '(02) 8527-5566',
            'email'        => 'Not publicly listed',
            'status'       => 'Pending',
            'category_id'  => 3,
            'address'      => 'Sta. Ana, Manila (District 6)',
        ],
        [
            'full_name'    => 'Nerissa RR. Lomeda',
            'organization' => 'Division of City Schools–Manila',
            'sector'       => 'Officer-in-Charge',
            'phone'        => '(02) 8527-5180',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 4,
            'address'      => 'Manila Education Center, Arroceros Forest Park, Manila',
        ],
        [
            'full_name'    => 'Mylene C. Villanueva',
            'organization' => 'Manila City Library',
            'sector'       => 'Officer-in-Charge',
            'phone'        => '(02) 5310-2618 / 5310-2573',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 4,
            'address'      => 'Mehan Garden, Ermita, Manila',
        ],
        [
            'full_name'    => 'John Daniel M. Layno',
            'organization' => 'Youth Development & Welfare Bureau',
            'sector'       => 'Officer-in-Charge',
            'phone'        => '(02) 8527-5220',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 4,
            'address'      => 'Manila City Hall Complex, Ermita, Manila',
        ],
        [
            'full_name'    => 'Milagros B. Delfin',
            'organization' => 'Parks Development Office',
            'sector'       => 'Officer-in-Charge',
            'phone'        => '(02) 3243-5211',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 4,
            'address'      => 'Aroceros Park, Manila',
        ],
        [
            'full_name'    => 'Alipio S. Morabe, Jr.',
            'organization' => 'Public Recreations Bureau',
            'sector'       => 'Officer-in-Charge',
            'phone'        => '(02) 5383-6882',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 4,
            'address'      => 'Rizal Memorial Coliseum Area, Manila',
        ],
        [
            'full_name'    => 'Dr. Grace H. Padilla',
            'organization' => 'Ospital ng Maynila Medical Center',
            'sector'       => 'OIC-Medical Center Chief / OIC-City Health Officer',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 4,
            'address'      => 'Quirino Ave cor Roxas Blvd, Malate, Manila',
        ],
        [
            'full_name'    => 'Jonvic Remulla',
            'organization' => 'Department of the Interior and Local Government',
            'sector'       => 'Secretary',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 5,
            'address'      => 'DILG-NAPOLCOM Center, EDSA corner Quezon Ave, Quezon City',
        ],
        [
            'full_name'    => 'Teodoro J. Herbosa',
            'organization' => 'Department of Health',
            'sector'       => 'Secretary',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 5,
            'address'      => 'San Lazaro Compound, Tayuman, Sta. Cruz, Manila',
        ],
        [
            'full_name'    => 'Rex Gatchalian',
            'organization' => 'Department of Social Welfare and Development',
            'sector'       => 'Secretary',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 5,
            'address'      => 'Batasan Pambansa Complex, Quezon City',
        ],
        [
            'full_name'    => 'Raphael P. M. Lotilla',
            'organization' => 'Department of Environment and Natural Resources',
            'sector'       => 'Secretary',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 5,
            'address'      => 'Visayas Avenue, Diliman, Quezon City',
        ],
        [
            'full_name'    => 'Vivencio “Vince” Dizon',
            'organization' => 'Department of Public Works and Highways',
            'sector'       => 'Secretary',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 5,
            'address'      => 'Bonifacio Drive, Port Area, Manila',
        ],
        [
            'full_name'    => 'Giovanni Lopez',
            'organization' => 'Department of Transportation',
            'sector'       => 'Secretary',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 5,
            'address'      => 'Clark Freeport Zone, Pampanga / Columbia Tower, Mandaluyong',
        ],
        [
            'full_name'    => 'PBGen Arnold E. Abad',
            'organization' => 'Manila Police District',
            'sector'       => 'District Director',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 5,
            'address'      => 'United Nations Avenue, Ermita, Manila',
        ],
        [
            'full_name'    => 'Victorino “Vic” A. Tan',
            'organization' => 'Manila Business Community',
            'sector'       => 'Business Sector Representative',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Pending',
            'category_id'  => 6,
            'address'      => 'Binondo, Manila (Chinatown Commercial District)',
        ],
        [
            'full_name'    => 'Engr. Arthur “Art” C. Co',
            'organization' => 'Manila Chamber / Business Association',
            'sector'       => 'President / Representative',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Pending',
            'category_id'  => 6,
            'address'      => 'Escolta St., Binondo, Manila',
        ],
        [
            'full_name'    => 'Rosalinda “Aling Linda” P. Santos',
            'organization' => 'Market Vendors Association',
            'sector'       => 'President / Representative',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Pending',
            'category_id'  => 6,
            'address'      => 'Divisoria / Paco Market Traders Alliance, Manila',
        ],
        [
            'full_name'    => 'Dr. Manuel “Manny” V. Ramos, MD',
            'organization' => 'Private Healthcare Sector',
            'sector'       => 'Healthcare Representative',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Pending',
            'category_id'  => 6,
            'address'      => 'Private Hospitals & Clinics Association, Manila',
        ],
        [
            'full_name'    => 'Jonathan “Jon” L. Yap',
            'organization' => 'Technology Sector',
            'sector'       => 'IT/Technology Representative',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Pending',
            'category_id'  => 6,
            'address'      => 'Tech & Digital Enterprises Hub, Manila',
        ],
        [
            'full_name'    => 'Patricia “Trisha” M. Ocampo',
            'organization' => 'Non-Government Organization',
            'sector'       => 'NGO Representative',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Pending',
            'category_id'  => 7,
            'address'      => 'Manila NGO Consortium, Ermita, Manila',
        ],
        [
            'full_name'    => 'Danilo “Ka Danny” B. Dela Rosa',
            'organization' => "People's Organization",
            'sector'       => 'President / Chairperson',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Pending',
            'category_id'  => 7,
            'address'      => 'Urban Poor Community Alliance, Tondo, Manila',
        ],
        [
            'full_name'    => 'Atty. Felixberto “Felix” R. Gomez',
            'organization' => 'Homeowners Association',
            'sector'       => 'President',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Pending',
            'category_id'  => 7,
            'address'      => 'Federation of Manila Homeowners Associations, Sta. Mesa, Manila',
        ],
        [
            'full_name'    => 'Engr. Corazon “Cora” D. Villafuerte',
            'organization' => 'Environmental Organization',
            'sector'       => 'Representative',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Pending',
            'category_id'  => 7,
            'address'      => 'Manila Bay Clean Habitat Coalition, Manila',
        ],
        [
            'full_name'    => 'Guillermo “Lolo Emong” T. Santos',
            'organization' => 'Senior Citizens Organization',
            'sector'       => 'President / Representative',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Pending',
            'category_id'  => 7,
            'address'      => 'Federation of Senior Citizens Associations of Manila (FSCAM), Manila',
        ],
        [
            'full_name'    => 'Arnel Eustacio M. Angeles',
            'organization' => 'Manila Disaster Risk Reduction Office',
            'sector'       => 'Director',
            'phone'        => '0950-700-3710',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 8,
            'address'      => 'Manila Disaster Risk Reduction and Management Office (MDRRMO), Manila City Hall',
        ],
        [
            'full_name'    => 'PBGen Arnold E. Abad',
            'organization' => 'Manila Police District',
            'sector'       => 'District Director',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 8,
            'address'      => 'United Nations Avenue, Ermita, Manila',
        ],
        [
            'full_name'    => 'F/Supt. Christine Cula',
            'organization' => 'Bureau of Fire Protection – Manila',
            'sector'       => 'Manila City Fire Marshal',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Pending',
            'category_id'  => 8,
            'address'      => 'BFP Manila District Headquarters, Quiricada St., Sta. Cruz, Manila',
        ],
        [
            'full_name'    => 'Dr. Grace H. Padilla',
            'organization' => 'Ospital ng Maynila Medical Center',
            'sector'       => 'OIC-Medical Center Chief',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Verified',
            'category_id'  => 8,
            'address'      => 'Quirino Ave cor Roxas Blvd, Malate, Manila',
        ],
        [
            'full_name'    => 'Capt. Ronald “Ron” V. Castillo',
            'organization' => 'Manila Emergency Services',
            'sector'       => 'Emergency Response Representative',
            'phone'        => 'Not publicly listed',
            'email'        => 'Not publicly listed',
            'status'       => 'Pending',
            'category_id'  => 8,
            'address'      => 'Manila Emergency Medical Services Command Center, Manila',
        ],
    ];

    $insertStmt = $pdo->prepare(
        'INSERT INTO stakeholders (full_name, email, phone, organization, sector, category_id, status, address, verified_at, created_at, updated_at) 
         VALUES (:full_name, :email, :phone, :organization, :sector, :category_id, :status, :address, NOW(), NOW(), NOW())'
    );
    $qrStmt = $pdo->prepare(
        'INSERT INTO qr_codes (stakeholder_id, code_value, created_at) VALUES (:sid, :code, NOW())'
    );

    foreach ($newStakeholders as $s) {
        $insertStmt->execute([
            ':full_name'    => $s['full_name'],
            ':email'        => $s['email'],
            ':phone'        => $s['phone'],
            ':organization' => $s['organization'],
            ':sector'       => $s['sector'],
            ':category_id'  => $s['category_id'],
            ':status'       => $s['status'],
            ':address'      => $s['address'],
        ]);
        $sid = (int)$pdo->lastInsertId();
        $code = 'STK-' . strtoupper(substr(bin2hex(random_bytes(4)), 0, 8));
        $qrStmt->execute([':sid' => $sid, ':code' => $code]);
    }

    setFlash('success', 'All stakeholders have been reset and successfully updated with Categories A to H (City Government, Barangay, Community, Public Institutions, National, Private, CSO, and Emergency Partners).');
} catch (Exception $e) {
    setFlash('danger', 'Error updating stakeholders: ' . $e->getMessage());
}

redirect(APP_URL . '/modules/stakeholders/index.php');
